app/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField


class Search(FlaskForm):
    title = StringField("Title")
    artist = StringField("Artist")
    submit = SubmitField("Search")

app/__init__.py
from flask import Flask, redirect, url_for
from .config import Config
from .chart_scraper import get_ranking
from .utils import get_tracks_id, get_tracks_info

ranking = get_ranking()
tracks_id = get_tracks_id(ranking)
tracks_info = []


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    app.secret_key = Config.SECRET_KEY
    global tracks_info
    tracks_info = get_tracks_info(tracks_id)

    from app.routes import rhythm
    app.register_blueprint(rhythm)
    app.register_error_handler(404, page_not_found)

    return app


def page_not_found(e):
    return redirect(url_for("rhythm.home"))

app/routes.py
from flask import Blueprint, render_template, redirect, url_for
from app import ranking, tracks_info
from .utils import get_track_id, get_track_info, get_date_week_later, get_artist_id, \
    get_artist_info, get_main_artist, search_track, get_related_artists, get_top_tracks
from .forms import Search
from .visualizations import get_song_vis
from bokeh.embed import components

rhythm = Blueprint("rhythm", __name__)


@rhythm.route("/", methods=["GET", "POST"])
def home():
    start_date = ranking[0]
    end_date = get_date_week_later(start_date)
    return render_template("home.html", title="Home", start_date=start_date, end_date=end_date,
                           ranking=ranking[1:], track_info=tracks_info)


@rhythm.route("/song/<artist_name>/<title>", methods=["GET", "POST"])
def song(artist_name, title):
    track_id = get_track_id(title)
    artists = get_main_artist(artist_name)

    if not track_id:
        return render_template("error.html", title=title)

    track_info, track_features = get_track_info(track_id)
    if track_info["name"][:5].lower() not in artist_name.lower():
        return render_template("error.html", title=title)

    plot = get_song_vis(track_features)
    script, div = components(plot)

    return render_template("song.html", title=title, song=title, artists=artists, track_info=track_info,
                           audio_features=track_features, script=script, div=div)


@rhythm.route("/artist/<name>", methods=["GET", "POST"])
def artist(name):
    main_artist = get_main_artist(name)[0]
    if main_artist != name:
        return redirect(url_for("rhythm.artist", name=main_artist))

    artist_id = get_artist_id(main_artist)
    if artist_id:
        artist_info = get_artist_info(artist_id)
        main_artist_name = artist_info["name"]
        image_link = artist_info["image_link"]
        genres = artist_info["genres"]
        related_artists = get_related_artists(artist_id)
        top_tracks = get_top_tracks(artist_id)
        return render_template("artist.html", title=main_artist_name, artist=main_artist_name,
                               image_link=image_link, genres=genres, related_artists=related_artists,
                               top_tracks=top_tracks)

    return render_template("error.html", title=main_artist)


@rhythm.route("/search", methods=["GET", "POST"])
def search():
    form = Search()
    if form.validate_on_submit():
        if form.title.data:
            return redirect(url_for("rhythm.results", query=form.title.data))

        elif form.artist.data:
            data = get_artist_id(form.artist.data, only_id=False)
            if data:
                artist_name = data[1]
                return redirect(url_for("rhythm.artist", name=artist_name))
            else:
                form.artist.data = ""

    return render_template("search.html", title="Search", form=form)


@rhythm.route("/results/<query>")
def results(query):
    data = search_track(query)
    if data:
        tracks_info_data = data[0]
        return render_template("results.html", title=query.capitalize(), query=query, track_info=tracks_info_data)
    else:
        return render_template("error.html", title=query)

app/templates/artist.html
{% extends "layout.html" %}
{% block content %}
    <br><br>
    <div class="text-center">
        <h1>{{ artist }}</h1>
        <h5>
            {% for genre in genres %}
                {{ genre }}
                {% if loop.index0 < genres|length - 1 %}
                        -
                {% endif %}
            {% endfor %}
        </h5>
    </div>
    <br><br>
    <div class="row justify-content-center">
        <img src="{{ image_link }}" height="250px" width="250px">
    </div>

    <br><br><br><br>
    <div class="text-center">
        <h2>Top Tracks</h2>
    </div>
    <br><br>
    <div class="row">
        {% for track in top_tracks %}
            <div class="col-sm">
                <a href="{{ url_for('rhythm.song', artist_name=artist, title=track['title']) }}">
                <img src="{{ track['image'] }}" height="160px" width="160px">
                </a>
            </div>
        {% endfor %}
    </div>

    <br><br><br><br>
    <div class="text-center">
        <h2>Related Artists</h2>
    </div>
    <br><br>
    <div class="row">
        {% for artist in related_artists %}
            <div class="col-sm">
                <a href="{{ url_for('rhythm.artist', name=artist['name']) }}">
                <img src="{{ artist['image'] }}" height="160px" width="160px">
                </a>
            </div>
        {% endfor %}
    </div>


{% endblock content %}

app/templates/error.html
{% extends "layout.html" %}
{% block content %}
    <br><br><br>
    <div class="text-center">
            <h1>Sorry. This song or artist can't be found.</h1>
    </div>

{% endblock content %}

app/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <br><br>

    <div>

        <br>
        <div class="text-center">
            <h1>TOP 20 OF THIS WEEK</h1>
            <h5>{{ start_date }} - {{ end_date }}</h5>
        </div>
        <br><br>

        <div class="row justify-content-center">
            {% for rank in ranking %}
                <div class="card w-75 mt-3">

                    <div class="card-header text-center">
                        <b>{{ loop.index0 + 1}}</b>
                    </div>

                    <div class="card-body row">
                        <div class="col-lg-10">
                            <h5 class="card-title">
                                <a href="{{ url_for('rhythm.song', artist_name=rank[1], title=rank[0]) }}">{{ rank[0] }}</a>
                            </h5>
                            <p class="card-text">{{ rank[1] }}</p>
                        </div>
                        <div class="col-2">
                            <img src="{{ track_info[loop.index0]["image"]["url"] }}" height="80px" width="80px" class="pull-right">
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>

    </div>


{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <style type="text/css">
        body { background: #f1f2f6 !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>

    <link
        href="http://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.css"
        rel="stylesheet" type="text/css">
    <link
        href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.4.0.min.css"
        rel="stylesheet" type="text/css">

    <script src="https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.4.0.min.js"></script>

    {% if title %}
        <title>{{ title }} - Rhythm</title>
    {% else %}
        <title>Rhythm</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
              <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="{{ url_for('rhythm.home') }}">Rhythm</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{{ url_for('rhythm.search') }}">Search</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{{ url_for('rhythm.home') }}">Charts</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
          <br><br><br>
          <div class="row justify-content-center">
            <div class="col-lg-10">

                {% block content %}{% endblock %}

            <br><br>
            </div>
          </div>
    </main>


<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

app/templates/results.html
{% extends "layout.html" %}
{% block content %}
    <br><br>

    <div>

        <br>
        <div class="text-center">
            <h1>Results for '{{ query }}'</h1>
        </div>
        <br><br><br>

        <div class="row justify-content-center">
            {% for track in track_info %}
                <div class="card w-75 mt-3">

                    <div class="card-header text-center">
                        <b>{{ loop.index0 + 1}}</b>
                    </div>

                    <div class="card-body row">
                        <div class="col-lg-10">
                            <h5 class="card-title">
                                <a href="{{ url_for('rhythm.song', artist_name=track['name'], title=track['song']) }}">
                                    {{ track["song"] }}
                                </a>
                            </h5>
                            <p class="card-text">{{ track["name"] }}</p>
                        </div>
                        <div class="col-2">
                            <img src="{{ track["image"]["url"] }}" height="80px" width="80px" class="pull-right">
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>

    </div>


{% endblock content %}

app/templates/search.html
{% extends "layout.html" %}
{% block content %}
    <br><br>
    <div class="text-center">
            <h1>Search</h1>
            <h6>Enter the title of a song or an artist.</h6>
    </div> <br><br>
    <div class="row justify-content-center">
    <div class="col-lg-8 justify-content-center">

        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {{ form.title(class="form-control form-control-lg") }}
                </div>
                <div class="row justify-content-center">
                    <h5>OR</h5>
                </div>
                <div class="form-group">
                    {{ form.artist.label(class="form-control-label") }}
                    {{ form.artist(class="form-control form-control-lg") }}
                </div>
            </fieldset>
            <div class="form-group row justify-content-center">
                {{ form.submit(class="btn btn-primary mb-2") }}
            </div>
        </form>

    </div>
    </div>


{% endblock content %}

app/templates/song.html
{% extends "layout.html" %}
{% block content %}
    <br><br>
    <div class="text-center">
            <h1>{{ song }}</h1>
            <h4>by
                {% for artist in artists %}
                    <a href="{{ url_for('rhythm.artist', name=artist) }}">
                    {{ artist }}
                    </a>
                    {% if loop.index0 < artists|length - 1 %}
                        &
                    {% endif %}
                {% endfor %}
            </h4>
    </div>
    <br><br>
    <div class="row justify-content-center">
        <img src="{{ track_info["image"]["url"] }}" height="250px" width="250px">
    </div>
    <br><br><br><br>
    <div class="text-center">
            <h1>Statistics</h1>
    </div><br><br>
    <div class="row justify-content-center">
            {{ div|safe }}
            {{ script|safe }}
    </div>

{% endblock content %}